export const GET_ORDER_BY_REDEMPTION_HASH = 'GET_ORDER_BY_REDEMPTION_HASH'
export const GET_ORDER_BY_REDEMPTION_HASH_STARTED = 'GET_ORDER_BY_REDEMPTION_HASH_STARTED'
export const GET_ORDER_BY_REDEMPTION_HASH_SUCCEEDED = 'GET_ORDER_BY_REDEMPTION_HASH_SUCCEEDED'
export const GET_ORDER_BY_REDEMPTION_HASH_FAILED = 'GET_ORDER_BY_REDEMPTION_HASH_FAILED'

export const getOrderByRedemptionHash = (redemptionHash) => ({
  type: GET_ORDER_BY_REDEMPTION_HASH,
  payload: {
    redemptionHash,
  },
})
