export const GET_DONATION_BY_CAUSE = 'GET_DONATION_BY_CAUSE'
export const GET_DONATION_BY_CAUSE_STARTED = 'GET_DONATION_BY_CAUSE_STARTED'
export const GET_DONATION_BY_CAUSE_SUCCEEDED = 'GET_DONATION_BY_CAUSE_SUCCEEDED'
export const GET_DONATION_BY_CAUSE_FAILED = 'GET_DONATION_BY_CAUSE_FAILED'

export const getDonationsByCause = (data) => ({
  type: GET_DONATION_BY_CAUSE,
  payload: data,
})
